#!/usr/bin/zsh

# Function to create .zshrc file with specified theme and plugins
create_preview_zshrc() {
    local zsh_rc_file="$1"
    shift
    local theme="$1"
    shift
    local theme_plugins=("$@")

    cat >"$zsh_rc_file" <<EOL
# Generated by preview_themes.zsh
ZSH_THEME="$theme"

plugins=(${theme_plugins[@]} )

source "\$ZSH/oh-my-zsh.sh"

if [[ -f ".venv/bin/activate" ]]; then
    source ".venv/bin/activate"
fi

# Function to handle navigation
function prev() {
    inc=\${1-1}
    if ((inc == 0)); then
        return
    fi
    if ((inc >= 128)) || ((inc < -128)); then
        echo "Step must be between -128 to 127"
        return
    fi
    exit \$((-(\$inc)))
}

function next() {
    inc=\${1-1}
    if ((inc == 0)); then
        return
    fi
    if ((inc > 128)) || ((inc <= -128)); then
        echo "Step must in -127 to 128"
        return
    fi
    exit inc
}

function stop() {
    exit 0
}

# Prevent Ctrl+D from immediately exiting the shell
setopt ignoreeof

# Create ZLE widgets
zle -N stop_widget stop
zle -N next_widget next
zle -N prev_widget prev

bindkey '^D' stop_widget
bindkey '^[[1;5D' prev_widget # Ctrl + Arrow Left
bindkey '^[[1;5C' next_widget # Ctrl + Arrow Right
EOL
}

# Function to preview Oh My Zsh themes
preview_omz_themes() {
    local temp_zdotdir="$(mktemp -d /tmp/zsh_theme_preview.XXXXXX)"
    local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/preview_omz_themes"
    local last_theme_file="$config_dir/last_theme"
    local zsh_rc_file="$temp_zdotdir/.zshrc"

    # Default options
    local reset=false
    local help=false
    local start_theme=""
    local preview_plugins=()
    local reset_opt help_opt theme_opt plugin_opt

    # Parse command line arguments using getopt
    zparseopts -D -E -- r=reset_opt -reset=reset_opt h=help_opt -help=help_opt t:=theme_opt -theme:=theme_opt p:=plugin_opt -plugin:=plugin_opt

    if (($#help_opt > 0)); then
        help=true
        echo "Usage: $0 [options]"
        echo "Options:"
        echo "  -r, --reset                Start from the beginning instead of resuming"
        echo "  -t THEME, --theme THEME    Start with the specified theme (name or index number)"
        echo "  -p PLUGIN, --plugin PLUGIN Activate the specified plugin(s)"
        echo "  -h, --help                 Display this help message"
        return 0
    fi

    if (($#reset_opt > 0)); then
        reset=true
    fi

    if (($#theme_opt > 0)); then
        # Extract the theme name/index (second element in the array)
        start_theme="${theme_opt[2]}"
    fi

    # Process plugin options (can be specified multiple times)
    if (($#plugin_opt > 0)); then
        # Extract plugins (second element in the array)
        preview_plugins+=(${plugin_opt[2]})
    fi

    echo "Theme preview script"
    echo "Press Ctrl + [right arrow | left arrow] to navigate to the next or previous theme"
    echo "Press Ctrl+C to exit the entire script"
    echo "Use --reset or -r to start from the beginning"
    echo ""

    # Source zsh configuration to make omz available
    source "$HOME/.zshrc"

    # Get all available themes
    # Store themes in an array
    local themes=($(omz theme list))

    # Find starting index - note: zsh arrays are 1-indexed
    local start_index=1

    # Otherwise, try to resume from last theme if not resetting
    if ! [[ -n "$start_theme" ]] && ! $reset; then
        # Create config directory if it doesn't exist
        [[ -d "$config_dir" ]] || mkdir -p "$config_dir"

        # Try to load last theme if it exists
        if [[ -f "$last_theme_file" ]]; then
            start_theme=$(cat "$last_theme_file")
        fi
    fi

    # If theme is populated, use that
    if [[ -n "$start_theme" ]]; then
        # Check if it's a number
        if [[ "$start_theme" =~ ^[0-9]+$ ]]; then
            # It's a number, perform bounds check and use it as an index
            if [[ $start_theme -ge 1 && $start_theme -le ${#themes[@]} ]]; then
                start_index=$start_theme
                echo "Starting with theme index: $start_index (${themes[$start_index]})"
            else
                echo "Invalid theme index: $start_theme. Must be between 1 and ${#themes[@]}"
                return 1
            fi
        else
            # It's a name, find its index
            local found=false
            for index in {1..${#themes[@]}}; do
                if [[ "${themes[$index]}" == "$start_theme" ]]; then
                    start_index=$index
                    found=true
                    echo "Starting with theme: $start_theme"
                    break
                fi
            done
            if ! $found; then
                echo "Theme '$start_theme' not found. Available themes:"
                echo "${themes[@]}"
                return 1
            fi
        fi
    fi

    # Initialize index
    local index=$start_index

    # Loop through themes using while true
    while true; do
        # Check if index is out of bounds
        if [[ $index -lt 1 ]]; then
            index=1
            echo "Already at the first theme."
        elif [[ $index -gt ${#themes[@]} ]]; then
            echo "Theme preview completed."
            break
        fi

        local theme="${themes[$index]}"
        echo "Setting theme to: $theme ($index/${#themes[@]}) [← Previous | Next →]"

        # Save current theme to config file
        [[ -d "$config_dir" ]] || mkdir -p "$config_dir"
        echo "$theme" >"$last_theme_file"

        # Create .zshrc with current theme and plugins
        create_preview_zshrc "$zsh_rc_file" "$theme" "${preview_plugins[@]}"

        # Start an interactive shell with our temporary zshrc
        ZSH=$ZSH ZDOTDIR=$temp_zdotdir zsh -i
        local exit_code=$?

        # Update index based on exit code
        if (($exit_code == 0)); then
            # Exit code 0 means stop the preview
            echo "Theme preview stopped."
            break
        elif (($exit_code > 128)); then
            # Go back theme. This applies to exit -1, for example
            index=$((index - (256 - $exit_code)))
        else
            # Any other exit code means continue to next theme
            index=$((index + $exit_code))
        fi
    done

    # Clean up temporary directory
    rm -rf "$temp_zdotdir"

    return 0
}

# Only execute the function if the script is run directly, not sourced
if ! [[ $ZSH_EVAL_CONTEXT =~ :file$ ]]; then
    preview_omz_themes "$@"
fi
